### ISSUE TITLE
بازی برای تلگرام 

### ISSUE THREAD

**Issue by javad94** [nainemom/faeze#1]
امکانش هست ساپورت بازی های تلگرام بهش اضافه بشه؟

**Comment by nainemom** [comment]
کل این بازی یه شوخی بود با عکس دفتر مشغی که توی توییتر پخش شده بود. نمیدونم. اگر که ایده‌ای به ذهنم برسه بازی جذاب‌تری بشه، حتما.

**Comment by javad94** [comment]
اره از جریانش خبر دارم. ممنون
