### ISSUE TITLE
ایده

### ISSUE THREAD

**Issue by babayaga94** [nainemom/faeze#3]
یعنی متاسفم توی کشوری زندگی میکنم که توی قرن بیست و یک اندازه یک الاغ فهم ندارن... این ایده شما بدرد خودتون میخوره احتمالا در بچگی صحنه تجاوز به مادرتون رو زیاد مشاهده کردین که الان بازیش رو ساختین... این ایده شاید توی اجداد خروس صفت شما صدق کنه ولی برای دیگران مفت نمی ارزه

**Comment by danialbehzadi** [comment]
😐

**Comment by shahabsaf1** [comment]
😐🔫
